version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:12.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: xmtest
    steps:
      - checkout
      - run:
          name: yarn-install
          command: yarn
      # - run:
      #     name: lint
      #     command: npm run lint
      # - run:
      #     name: build
      #     command: npm run build

workflows:
  version: 2
  test:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
